### ISSUE TITLE
Adapt a/an before AI/BS

### ISSUE THREAD

**Issue by phipsgabler** [brenhinkeller/AI-to-BS#1]
"<span>A</span>I" -> "BS" unfortunately breaks the rules of "a"/"an": 

![Screenshot from 2022-11-10 09-26-24](https://user-images.githubusercontent.com/7878215/201039528-c1c661b4-0c52-4f8b-a2a1-35377ee26245.png)

Would it make sense to also replace them before the BS pattern?

**Comment by brenhinkeller** [comment]
Ahh, great idea -- let's do it!
